### ISSUE TITLE
Can't compile mgclient on Fedora 37

### ISSUE THREAD

**Issue by Elvino00** [memgraph/mgclient#51]
Hi,
When I try to compile mgclient on my pc (Fedora 37 x64 bit NOT ARM) i get this cmake error:
![Screenshot from 2023-02-22 18-56-07](https://user-images.githubusercontent.com/74961430/220715500-4db041bf-118f-4f47-bad8-eb94da5c800f.png)

Here is the log file: 
[CMakeOutput.log](https://github.com/memgraph/mgclient/files/10806921/CMakeOutput.log)

**Comment by gitbuda** [comment]
Hi @Elvino00! Thanks for reporting. This is interesting. It seems like there are multiple problems on Fedora (so far, we haven't tested on Fedora). I'll try to recreate it soon (latest in the next day or so), but this seems like something easy to fix.

What's your version of CMake?

**Comment by Elvino00** [comment]
> Hi @Elvino00! Thanks for reporting. This is interesting. It seems like there are multiple problems on Fedora (so far, we haven't tested on Fedora). I'll try to recreate it soon (latest in the next day or so), but this seems like something easy to fix.
> 
> What's your version of CMake?

cmake version 3.25.2

**Comment by gitbuda** [comment]
I've run Fedora 37 in a Docker container. Please take a look at the config below, and it seems to be working. The whole error message on your end seems very weird because the `project` call is there, Linux should be detected because the standard CMake command is used for that... Long story short, I'm not sure what is happening...

Could you try to pull the latest commit from mgclient master branch + try to build and/or try to update CMake to `3.26.0-rc`, which should be available on the regular Fedora repo (I haven't added any specific repo)?

Also, happy to jump on a quick call at some point if that would be easier 😄

![Screenshot 2023-02-22 at 9 55 04 PM](https://user-images.githubusercontent.com/4950251/220757062-600cdbc9-ada7-4b86-996b-3a3420ee186e.png)

**Comment by gitbuda** [comment]
Ahaaa, @Elvino00, I've figured it out! The problem is `build` folder is created inside the `src` folder. That won't work because CMake needs a top-level `CMakeLists.txt` file. Please create the `build` folder in the project root folder and then rerun everything, so
```
git clone https://github.com/memgraph/mgclient.git
cd mgclient
mkdir build && cd build
cmake ..
make
```

**Comment by Elvino00** [comment]
> Ahaaa, @Elvino00, I've figured it out! The problem is `build` folder created inside the `src` folder. That won't work because CMake needs a top-level `CMakeLists.txt` file. Please create the `build` folder in the project root folder and then rerun everything, so
> 
> ```
> git clone https://github.com/memgraph/mgclient.git
> cd mgclient
> mkdir build && cd build
> cmake ..
> make
> ```

According to these three images, libraries should have been installed

![cmake-compile](https://user-images.githubusercontent.com/74961430/220937007-74ddea3a-a9d2-47ba-9f5a-982341f07be2.jpg)
![make compile](https://user-images.githubusercontent.com/74961430/220937018-cd22090d-998c-49f7-b81e-6f2e8b80dea4.jpg)
![make install](https://user-images.githubusercontent.com/74961430/220937021-04a23588-44b9-4ecf-b129-30893e90a314.jpg)

**Comment by Elvino00** [comment]
Please @gitbuda I kindly ask you to specify to build in top directory in README.md file

**Comment by Elvino00** [comment]
> #52 is this more clear?

Yes, but there's something I don't understand. When i Try to compile your example file "basic.c" with command gcc -o basic basic.c I get these errors:

![image](https://user-images.githubusercontent.com/74961430/220951223-aa744d58-ae1a-48a2-9e0f-62f3c75014f6.png)


Am I compiling this wrong?

**Comment by gitbuda** [comment]
The issue here is that the example needs to link the `mgclient` as a library. That can be done by the `-l` flag, e.g. `gcc -o basic -lmgclient basic.c` (not 100% sure because I haven't tested that, more details about linking -> https://www.rapidtables.com/code/linux/gcc/gcc-l.html)

On the other hand, all that work is already being done, you just have to enable tests (because examples are compiled if tests are active):
```
cd build
cmake -DBUILD_TESTING=ON ..
make
```

**Comment by Elvino00** [comment]
> 

After make command, on the last rows of the terminal I get this error:

![image](https://user-images.githubusercontent.com/74961430/220957685-4534aa16-2f99-4300-805d-5f8dafc4913a.png)

**Comment by gitbuda** [comment]
Maybe something got broken inside the `build` folder... Could you remove the entire content of the build folder and run commands from scratch?

**Comment by Elvino00** [comment]
> Maybe something got broken inside the `build` folder... Could you remove the entire content of the build folder and run commands from scratch?

I tried. I always get the same error

**Comment by gitbuda** [comment]
Yes, I also got the same error on my Fedora 37 setup, so I think this is a valid bug in the `CMake` config. If this is not blocking for you, I'll investigate/resolve that in the following few days? You don't have to build tests if the command above is working for you 😄

**Comment by Elvino00** [comment]
> Yes, I also got the same error on my Fedora 37 setup, so I think this is a valid bug in the `CMake` config. If this is not blocking for you, I'll investigate/resolve that in the following few days? You don't have to build tests if the command above is working for you smile

No, no problem, do your investigations. At this point I'll build the library with the command I gave you. I don't know if it can be useful to add in the README, you choose.

**Comment by gitbuda** [comment]
The problem is that the `gtest/lib` folder on Fedora is called `gtest/lib64`. The CMake config has to work in both cases. Thanks for reporting! I'll think of how to make all that a bit better 😄

![Screenshot 2023-02-23 at 5 38 01 PM](https://user-images.githubusercontent.com/4950251/220971783-118866d6-b010-4cb6-beb3-8f19c55cae3e.png)

**Comment by Elvino00** [comment]
> The problem is that the `gtest/lib` folder on Fedora is called `gtest/lib64`. The CMake config has to work in both cases. Thanks for reporting! I'll think of how to make all that a bit better smile
> 
> ![Screenshot 2023-02-23 at 5 38 01 PM](https://user-images.githubusercontent.com/4950251/220971783-118866d6-b010-4cb6-beb3-8f19c55cae3e.png)

You're welcome!

**Comment by katarinasupe** [comment]
@Elvino00 thank you so much for reporting this and helping us to make the developer experience as smooth as possible. If you have any more questions, feel free to [join Memgraph's Discord community](https://www.discord.gg/memgraph) 😄

**Comment by Elvino00** [comment]
> @Elvino00 thank you so much for reporting this and helping us to make the developer experience as smooth as possible. If you have any more questions, feel free to [join Memgraph's Discord community](https://www.discord.gg/memgraph) smile

Can eventual bugs be reported on that community?

**Comment by katarinasupe** [comment]
@Elvino00 yes, they can, although if you suspect something is a bug and have steps to reproduce, it's great to report it directly to the appropriate repository. The community can be helpful for questions about the usage and general conversations about graph technology.
